name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/nek000/distrobox-dev:2025.6.1

    - name: Push Docker image
      run: docker push ghcr.io/nek000/distrobox-dev:2025.6.1