name: Build and Push Docker image with YYYY.M.N Tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to read git history and tags

      - name: Get date and version tag
        id: tag
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          
          # Find the highest N for the current year and month
          PREFIX="$YEAR.$MONTH."
          LAST=$(git tag --list "${PREFIX}*" | sed "s/^$PREFIX//" | sort -nr | head -n 1)
          if [[ -z "$LAST" ]]; then
            NEXT=1
          else
            NEXT=$((LAST + 1))
          fi
          VERSION="$YEAR.$MONTH.$NEXT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"
         
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/nek000/distrobox-dev:${{ env.VERSION }}